import { Balloon } from "./Balloon";
import { GameAudio } from "./audio";
import { InputController } from "./InputController";
import { Pillar } from "./Pillar";
import { PHYSICS_STEP, type ControlMode, type Rect } from "./types";
import { UIManager } from "./UIManager";

type Cloud={x:number;y:number;s:number;a:number;v:number};type Ember={x:number;y:number;vx:number;vy:number;life:number;max:number};type Particle={x:number;y:number;vx:number;vy:number;life:number;max:number;r:number};
function aabb(a:Rect,b:Rect):boolean{return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function difficulty(score:number,w:number,h:number){const early=Math.min(score,9)/9;const late=Math.max(0,score-9);const speed=w*(0.48+early*0.1+Math.min(late*0.032,0.3));const balloonH=h*0.125;const gapMul=2.28-early*0.22-Math.min(late*0.065,0.58);const gapHeight=Math.max(balloonH*1.62,balloonH*gapMul);const spacing=w*(1.08-early*0.1-Math.min(late*0.038,0.3));const maxOffset=h*(0.14+early*0.05+Math.min(late*0.014,0.11));return{speed,gapHeight,spacing,maxOffset};}
export class Game{
 readonly ui=new UIManager();readonly audio=new GameAudio();private canvas:HTMLCanvasElement;private ctx:CanvasRenderingContext2D;private balloon:Balloon;private pillars:Pillar[]=[];private input:InputController;private raf=0;private last=0;private acc=0;private w=390;private h=844;private time=0;private nextId=1;private dyingT=0;private hitstop=0;private trauma=0;private clouds:Cloud[]=[];private embers:Ember[]=[];private burst:Particle[]=[];private reducedMotion=false;private destroyed=false;private onVis:(()=>void)|null=null;private onResize:(()=>void)|null=null;
 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas 2D is not available");this.ctx=ctx;this.balloon=new Balloon(0,0);this.input=new InputController(canvas,this);this.reducedMotion=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches??false;this.resize();this.seedDecor();this.input.attach();this.bindWindow();this.audio.setEnabled(this.ui.soundEnabled);window.__sunsetBalloon=this;}
 get screen():string{return this.ui.screen;}get controlMode():string{return this.ui.controlMode;}
 hitActivePillar(x:number,y:number):boolean{if(this.balloon.dying)return false;const p=this.activePillar();if(!p)return false;const slop=Math.max(16,p.width*0.45);return p.containsTouch(x,y,slop);}
 nudgeActiveGap(deltaY:number):void{if(this.balloon.dying)return;const p=this.activePillar();if(!p)return;const scale=this.h/844;p.moveGap(deltaY*scale,false);this.audio.tap();}
 swipeActiveGap(deltaY:number):void{if(this.balloon.dying)return;const p=this.activePillar();if(!p)return;p.moveGap(deltaY,true);}
 start():void{this.stopLoop();this.last=0;this.raf=requestAnimationFrame(this.frame);}
 destroy():void{this.destroyed=true;this.stopLoop();this.input.detach();if(this.onVis)document.removeEventListener("visibilitychange",this.onVis);if(this.onResize)window.removeEventListener("resize",this.onResize);if(window.__sunsetBalloon===this)delete window.__sunsetBalloon;}
 startPlay():void{this.audio.unlock();this.audio.ui();this.resetRun();this.ui.setScreen("play");this.ui.setScore(0);this.ensureLoop();}
 openMenu():void{this.audio.ui();this.pillars=[];this.burst=[];this.balloon.reset(this.w,this.h);this.ui.setScreen("menu");this.ensureLoop();}
 openSettings():void{this.audio.ui();this.ui.setScreen("settings");this.ensureLoop();}
 openHelp():void{this.audio.ui();this.ui.setScreen("help");this.ensureLoop();}
 pause():void{if(this.ui.screen!=="play")return;this.audio.ui();this.ui.setScreen("paused");this.stopLoop();this.draw();}
 resume():void{if(this.ui.screen!=="paused")return;this.audio.ui();this.audio.unlock();this.ui.setScreen("play");this.last=0;this.ensureLoop();}
 restart():void{this.audio.unlock();this.startPlay();}
 setSound(on:boolean):void{this.ui.setSound(on);this.audio.setEnabled(on);this.audio.ui();}
 setControlMode(mode:ControlMode):void{this.ui.setControlMode(mode);this.audio.ui();}
 private bindWindow():void{this.onVis=()=>{if(document.hidden&&this.ui.screen==="play")this.pause();else this.audio.resume();};document.addEventListener("visibilitychange",this.onVis);this.onResize=()=>this.resize();window.addEventListener("resize",this.onResize);}
 private resize():void{const parent=this.canvas.parentElement??this.canvas;const cssW=Math.max(1,parent.clientWidth||window.innerWidth);const cssH=Math.max(1,parent.clientHeight||window.innerHeight);const dpr=Math.min(window.devicePixelRatio||1,2.5);this.canvas.width=Math.round(cssW*dpr);this.canvas.height=Math.round(cssH*dpr);this.canvas.style.width=`${cssW}px`;this.canvas.style.height=`${cssH}px`;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=cssW;this.h=cssH;this.balloon.layout(cssW,cssH);for(const p of this.pillars)p.canvasH=cssH;}
 private seedDecor():void{this.clouds=[{x:0.18,y:0.16,s:0.9,a:0.07,v:0.012},{x:0.72,y:0.11,s:1.15,a:0.05,v:0.008},{x:0.48,y:0.22,s:0.7,a:0.06,v:0.01}];this.embers=[];for(let i=0;i<10;i++)this.spawnEmber(true);}
 private spawnEmber(anywhere=false):void{this.embers.push({x:this.w*(0.35+Math.random()*0.3),y:anywhere?this.h*(0.45+Math.random()*0.5):this.h*0.92,vx:(Math.random()-0.5)*8,vy:-12-Math.random()*18,life:anywhere?Math.random():0,max:3.5+Math.random()*2});}
 private resetRun():void{this.pillars=[];this.burst=[];this.dyingT=0;this.hitstop=0;this.trauma=0;this.acc=0;this.balloon.reset(this.w,this.h);this.spawnPillar(true);}
 private spawnPillar(first=false):void{const d=difficulty(this.ui.score,this.w,this.h);const width=Math.max(32,this.w*0.085);const x=first?this.w-width*0.2:this.w+width;const sign=Math.random()<0.5?-1:1;const mag=(0.35+Math.random()*0.65)*d.maxOffset;let gapY=this.balloon.y+sign*mag;const half=d.gapHeight/2;gapY=Math.max(12+half,Math.min(this.h-12-half,gapY));const speed=first?d.speed*0.92:d.speed;this.pillars.push(new Pillar(x,gapY,d.gapHeight,speed,width,this.h,this.nextId++));}
 private activePillar():Pillar|null{let best:Pillar|null=null;for(const p of this.pillars){if(p.passed)continue;if(!best||p.x<best.x)best=p;}return best;}
 private stopLoop():void{if(this.raf)cancelAnimationFrame(this.raf);this.raf=0;}
 private ensureLoop():void{if(this.destroyed)return;if(!this.raf){this.last=0;this.raf=requestAnimationFrame(this.frame);}}
 private frame=(t:number):void=>{if(this.destroyed)return;this.raf=requestAnimationFrame(this.frame);if(!this.last){this.last=t;this.draw();return;}let dt=(t-this.last)/1000;this.last=t;dt=Math.min(dt,0.1);const screen=this.ui.screen;if(screen==="paused")return;if(screen==="play"){this.acc+=dt;while(this.acc>=PHYSICS_STEP){this.fixedUpdate(PHYSICS_STEP);this.acc-=PHYSICS_STEP;}}else{this.time+=dt;this.updateDecor(dt);}this.draw();};
 private fixedUpdate(dt:number):void{if(this.hitstop>0){this.hitstop-=dt;return;}this.time+=dt;this.trauma=Math.max(0,this.trauma-dt*2.4);if(this.balloon.dying){this.balloon.update(dt);this.dyingT+=dt;this.updateDecor(dt);this.updateBurst(dt);if(this.dyingT>0.95){this.ui.noteBest(this.ui.score);this.ui.setScreen("gameover");}return;}for(const p of this.pillars)p.update(dt,true);const bounds=this.balloon.getBounds();for(const p of this.pillars){if(!p.passed&&p.x+p.width<bounds.x){p.passed=true;if(!p.scored){p.scored=true;this.ui.setScore(this.ui.score+1);this.audio.score();}}if(!this.balloon.dying&&(aabb(bounds,p.getTopRect())||aabb(bounds,p.getBottomRect()))){this.crash();break;}}this.pillars=this.pillars.filter(p=>p.x+p.width>-40);const newest=this.pillars[this.pillars.length-1];const d=difficulty(this.ui.score,this.w,this.h);if(!newest||newest.x<this.w-d.spacing)this.spawnPillar(false);this.updateDecor(dt);this.updateBurst(dt);}
 private crash():void{this.audio.crash();this.balloon.beginFall();this.dyingT=0;this.hitstop=this.reducedMotion?0:0.08;this.trauma=this.reducedMotion?0:0.7;const bb=this.balloon.getBounds();for(let i=0;i<14;i++){const ang=Math.random()*Math.PI*2;const sp=40+Math.random()*120;this.burst.push({x:bb.x+bb.w/2,y:bb.y+bb.h/2,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp-40,life:0,max:0.45+Math.random()*0.3,r:2+Math.random()*3});}}
 private updateDecor(dt:number):void{for(const c of this.clouds){c.x-=c.v*dt;if(c.x<-0.25)c.x=1.2;}if(this.embers.length<10)this.spawnEmber(false);for(const e of this.embers){e.x+=e.vx*dt;e.y+=e.vy*dt;e.life+=dt;}this.embers=this.embers.filter(e=>e.life<e.max&&e.y>-10);}
 private updateBurst(dt:number):void{for(const p of this.burst){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=420*dt;p.life+=dt;}this.burst=this.burst.filter(p=>p.life<p.max);}
 private draw():void{const ctx=this.ctx,{w,h}=this;ctx.clearRect(0,0,w,h);let ox=0,oy=0;if(this.trauma>0&&!this.reducedMotion){const mag=this.trauma*this.trauma*10;ox=(Math.random()*2-1)*mag;oy=(Math.random()*2-1)*mag;}ctx.save();ctx.translate(ox,oy);this.drawBackground(ctx);const active=this.activePillar();const showWorld=this.ui.screen==="play"||this.ui.screen==="paused"||this.ui.screen==="gameover";if(showWorld){for(const p of this.pillars)p.draw(ctx,p===active&&this.ui.screen==="play");if(this.ui.screen!=="gameover")this.balloon.draw(ctx,this.time);this.drawBurst(ctx);}ctx.restore();}
 private drawBackground(ctx:CanvasRenderingContext2D):void{const{w,h}=this;const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#4A2C4A");g.addColorStop(0.45,"#8E4350");g.addColorStop(1,"#D84315");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const sunX=w*0.5,sunY=h*0.9,sunR=Math.min(w,h)*0.42;const glow=ctx.createRadialGradient(sunX,sunY,sunR*0.2,sunX,sunY,sunR*1.35);glow.addColorStop(0,"rgba(255,180,70,0.55)");glow.addColorStop(0.45,"rgba(255,120,40,0.18)");glow.addColorStop(1,"rgba(255,80,20,0)");ctx.fillStyle=glow;ctx.fillRect(0,h*0.4,w,h*0.6);ctx.fillStyle="#F08A2A";ctx.beginPath();ctx.arc(sunX,sunY,sunR,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(255,210,90,0.35)";ctx.beginPath();ctx.arc(sunX,sunY,sunR*0.72,0,Math.PI*2);ctx.fill();for(const c of this.clouds){ctx.fillStyle=`rgba(255,220,200,${c.a})`;const cx=c.x*w,cy=c.y*h,s=c.s*w*0.12;ctx.beginPath();ctx.ellipse(cx,cy,s,s*0.38,0,0,Math.PI*2);ctx.ellipse(cx+s*0.45,cy+s*0.05,s*0.7,s*0.3,0,0,Math.PI*2);ctx.ellipse(cx-s*0.4,cy+s*0.08,s*0.55,s*0.26,0,0,Math.PI*2);ctx.fill();}for(const e of this.embers){const t=1-e.life/e.max;ctx.fillStyle=`rgba(255,170,80,${0.18*t})`;ctx.beginPath();ctx.arc(e.x,e.y,1.6,0,Math.PI*2);ctx.fill();}}
 private drawBurst(ctx:CanvasRenderingContext2D):void{for(const p of this.burst){const t=1-p.life/p.max;ctx.fillStyle=`rgba(255,170,70,${0.8*t})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r*t,0,Math.PI*2);ctx.fill();}}
}
declare global { interface Window { __sunsetBalloon?: Game; } }
