const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),menu=document.getElementById('menu'),hud=document.getElementById('hud'),over=document.getElementById('gameover'),scoreEl=document.getElementById('score'),finalEl=document.getElementById('finalScore');const balloonImg=new Image();balloonImg.src='design/game-assets/balloon.png';let hasBalloon=false;balloonImg.onload=()=>hasBalloon=true;
let W=0,H=0,dpr=1,state='menu',last=0,score=0,paused=false,spawnTimer=0,difficulty=0,moveUp=true;const balloon={x:.27,y:.5,r:34};let pillars=[];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);balloon.r=Math.max(25,Math.min(42,W*.075))}addEventListener('resize',resize);resize();
function reset(){score=0;difficulty=0;spawnTimer=.3;pillars=[];balloon.y=.5;moveUp=true;state='playing';paused=false;menu.classList.add('hidden');over.classList.add('hidden');hud.classList.remove('hidden');scoreEl.textContent=0}
function addPillar(){const gapH=Math.max(H*.20,H*(.34-difficulty*.055));const margin=H*.08;const gapY=margin+Math.random()*Math.max(1,H-gapH-margin*2);pillars.push({x:W+70,w:Math.max(64,W*.16),gapY,gapH,scored:false,speed:Math.max(170,W*.42)+difficulty*22})}
function update(dt){if(state!=='playing'||paused)return;difficulty=Math.min(2,score/35);spawnTimer-=dt;if(spawnTimer<=0){addPillar();spawnTimer=Math.max(.95,1.45-difficulty*.25)}for(const p of pillars){p.x-=p.speed*dt;const target=moveUp?H*.08:H*.68;p.gapY+=(target-p.gapY)*Math.min(1,dt*3.2)}pillars=pillars.filter(p=>p.x+p.w>-20);for(const p of pillars){if(!p.scored&&p.x+p.w<balloon.x-balloon.r){p.scored=true;score++;scoreEl.textContent=score}}for(const p of pillars){if(balloon.x+balloon.r>p.x&&balloon.x-balloon.r<p.x+p.w&&(balloon.y-balloon.r<p.gapY||balloon.y+balloon.r>p.gapY+p.gapH)){gameOver();return}}}
function gameOver(){state='over';hud.classList.add('hidden');finalEl.textContent=score;over.classList.remove('hidden')}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#4A2C4A');g.addColorStop(.55,'#9C3F2E');g.addColorStop(1,'#D84315');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#FFC107';ctx.beginPath();ctx.arc(W*.78,H*.22,Math.min(W,H)*.11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff12';for(let i=0;i<8;i++){ctx.beginPath();ctx.arc((i*137)%W,H*.3+(i*91)%H*.5,2,0,7);ctx.fill()}}
function drawPillar(p){ctx.fillStyle='#5D4037';ctx.strokeStyle='#211817';ctx.lineWidth=5;const parts=[[p.x,0,p.w,p.gapY],[p.x,p.gapY+p.gapH,p.w,H-(p.gapY+p.gapH)]];for(const [x,y,w,h] of parts){ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h)}ctx.fillStyle='#795548';ctx.fillRect(p.x-8,p.gapY-18,p.w+16,18);ctx.strokeRect(p.x-8,p.gapY-18,p.w+16,18);ctx.fillRect(p.x-8,p.gapY+p.gapH,p.w+16,18);ctx.strokeRect(p.x-8,p.gapY+p.gapH,p.w+16,18)}
function drawBalloon(){const x=balloon.x,y=balloon.y,r=balloon.r;if(hasBalloon){const s=r*2.7;ctx.drawImage(balloonImg,x-s/2,y-s*.58,s,s)}else{ctx.save();ctx.translate(x,y);ctx.fillStyle='#E6D5B8';ctx.strokeStyle='#332820';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-r*.2,r,r*1.15,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#5D4037';ctx.fillRect(-r*.38,r*.78,r*.76,r*.4);ctx.fillStyle='#FF5722';ctx.beginPath();ctx.moveTo(-5,r*.78);ctx.quadraticCurveTo(0,r*1.25,5,r*.78);ctx.fill();ctx.restore()}}
function render(){drawBackground();for(const p of pillars)drawPillar(p);drawBalloon()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function tap(){if(state==='menu')return reset();if(state==='over')return reset();if(state==='playing'&&!paused){moveUp=!moveUp}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();tap()});document.getElementById('play').onclick=reset;document.getElementById('restart').onclick=reset;document.getElementById('home').onclick=()=>{state='menu';over.classList.add('hidden');hud.classList.add('hidden');menu.classList.remove('hidden')};document.getElementById('pause').onclick=()=>paused=!paused;
