(()=>{"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),pauseBtn=document.getElementById("pauseButton");
const menu=document.getElementById("menu"),settings=document.getElementById("settingsPanel"),help=document.getElementById("helpPanel"),over=document.getElementById("gameOver"),pause=document.getElementById("pausePanel"),scene=document.getElementById("scene");
const W=470,H=764,TOP=70,BOTTOM=694,GAP=154,PW=50,STEP=32;let scaleX=1,scaleY=1,last=0,running=false,paused=false,score=0,drag=null,pointerId=null;
const balloon={x:105,y:382,w:92,h:138};const balloonImg=new Image();balloonImg.src="design/app-icon/icon_1024_transparent.png";let pillar;
function resize(){scaleX=innerWidth/W;scaleY=innerHeight/H;canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width="100vw";canvas.style.height="100vh";ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);positionPause()}function positionPause(){pauseBtn.style.left="calc(100vw - 64px)";pauseBtn.style.top="18px"}addEventListener("resize",resize);resize();
function world(e){return{x:e.clientX/scaleX,y:e.clientY/scaleY}}
function makePillar(){return{x:W+35,gapY:298,w:PW,gapH:GAP,passed:false}}
function reset(){pillar=makePillar();pillar.x=210}
function clampGap(){pillar.gapY=Math.max(TOP,Math.min(BOTTOM-pillar.gapH,pillar.gapY))}
function nudgeGap(){pillar.gapY-=STEP;clampGap()}
function dragGap(y){pillar.gapY+=(y-pillar._lastY);pillar._lastY=y;clampGap()}
function currentSpeed(){return 94+Math.min(score*4.2,128)}
function start(){menu.classList.add("hidden");settings.classList.add("hidden");help.classList.add("hidden");over.classList.add("hidden");pause.classList.add("hidden");scene.classList.add("hidden");canvas.classList.remove("hidden");pauseBtn.classList.add("show");score=0;reset();running=true;paused=false;last=performance.now();requestAnimationFrame(loop)}
function end(){running=false;paused=false;pause.classList.add("hidden");pauseBtn.classList.remove("show");document.getElementById("finalScore").textContent=score;over.classList.remove("hidden");scene.classList.remove("hidden");canvas.classList.add("hidden")}
function intersects(a,b){return a.x<a.x+a.w&&a.x+a.w>b.x&&a.y<a.y+a.h&&a.y+a.h>b.y}
function collision(){const bx=balloon.x-balloon.w*.32,by=balloon.y-balloon.h*.36,bw=balloon.w*.64,bh=balloon.h*.72;const left=pillar.x-2,right=pillar.x+pillar.w+2;const horizontal=bx+bw>left&&bx<right;if(!horizontal)return false;const topHit=by<pillar.gapY;const bottomHit=by+bh>pillar.gapY+pillar.gapH;return topHit||bottomHit}
function drawBalloon(){if(balloonImg.complete)ctx.drawImage(balloonImg,balloon.x-balloon.w/2,balloon.y-balloon.h/2,balloon.w,balloon.h)}
function drawPillar(){ctx.fillStyle="#30231f";ctx.strokeStyle="#17110f";ctx.lineWidth=4;ctx.fillRect(pillar.x,0,pillar.w,pillar.gapY);ctx.strokeRect(pillar.x,0,pillar.w,pillar.gapY);ctx.fillRect(pillar.x,pillar.gapY+pillar.gapH,pillar.w,H-pillar.gapY-pillar.gapH);ctx.strokeRect(pillar.x,pillar.gapY+pillar.gapH,pillar.w,H-pillar.gapY-pillar.gapH);ctx.fillRect(pillar.x-8,pillar.gapY-9,pillar.w+16,10);ctx.strokeRect(pillar.x-8,pillar.gapY-9,pillar.w+16,10);ctx.fillRect(pillar.x-8,pillar.gapY+pillar.gapH,pillar.w+16,10);ctx.strokeRect(pillar.x-8,pillar.gapY+pillar.gapH,pillar.w+16,10)}
function drawCloud(x,y,s,a){ctx.save();ctx.globalAlpha=a;ctx.fillStyle="#f39a73";ctx.beginPath();ctx.ellipse(x,y,s*1.5,s*.45,0,0,Math.PI*2);ctx.ellipse(x-s*.75,y+4,s*.75,s*.34,0,0,Math.PI*2);ctx.ellipse(x+s*.65,y+3,s*.8,s*.38,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.save();ctx.clearRect(0,0,innerWidth,innerHeight);ctx.scale(scaleX,scaleY);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#21103b");g.addColorStop(.34,"#51204d");g.addColorStop(.66,"#c64b2d");g.addColorStop(1,"#f58225");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<24;i++){const x=(i*83)%W,y=45+(i*57)%280;ctx.fillStyle="rgba(255,220,190,.18)";ctx.fillRect(x,y,2,2)}ctx.fillStyle="#ff9f1c";ctx.beginPath();ctx.arc(W/2,665,126,0,Math.PI*2);ctx.fill();drawCloud(72,238,24,.28);drawCloud(392,286,30,.24);drawCloud(265,184,20,.16);const mg=ctx.createLinearGradient(0,560,0,H);mg.addColorStop(0,"#4a2450");mg.addColorStop(1,"#211733");ctx.fillStyle=mg;ctx.beginPath();ctx.moveTo(0,H);ctx.lineTo(0,635);ctx.lineTo(55,575);ctx.lineTo(100,620);ctx.lineTo(158,555);ctx.lineTo(220,625);ctx.lineTo(285,570);ctx.lineTo(340,620);ctx.lineTo(405,565);ctx.lineTo(W,625);ctx.lineTo(W,H);ctx.closePath();ctx.fill();ctx.fillStyle="#1c1630";ctx.beginPath();ctx.moveTo(0,H);ctx.lineTo(0,680);ctx.lineTo(75,625);ctx.lineTo(130,670);ctx.lineTo(205,610);ctx.lineTo(275,675);ctx.lineTo(350,615);ctx.lineTo(420,675);ctx.lineTo(W,635);ctx.lineTo(W,H);ctx.closePath();ctx.fill();drawPillar();drawBalloon();ctx.fillStyle="#fff";ctx.font="900 48px Tahoma,Arial";ctx.textAlign="left";ctx.fillText(score,40,76);ctx.restore()}
function loop(t){if(!running)return;if(paused){last=t;requestAnimationFrame(loop);return}const dt=Math.min(.033,(t-last)/1000);last=t;pillar.x-=currentSpeed()*dt;if(pillar.x+pillar.w<0){pillar.x=W+55;pillar.gapY=TOP+Math.random()*(BOTTOM-pillar.gapH-TOP);pillar.passed=false}if(!pillar.passed&&pillar.x+pillar.w<balloon.x){pillar.passed=true;score++}if(collision()){end();return}draw();requestAnimationFrame(loop)}
canvas.addEventListener("pointerdown",e=>{if(!running||paused)return;const q=world(e);if(q.x<pillar.x-30||q.x>pillar.x+pillar.w+30)return;drag=pillar;pointerId=e.pointerId;pillar._lastY=q.y;nudgeGap();canvas.setPointerCapture?.(e.pointerId);e.preventDefault()});
canvas.addEventListener("pointermove",e=>{if(!drag||e.pointerId!==pointerId)return;dragGap(world(e).y);e.preventDefault()});
function endPointer(e){if(e.pointerId!==pointerId)return;drag=null;pointerId=null}canvas.addEventListener("pointerup",endPointer);canvas.addEventListener("pointercancel",endPointer);
function pauseGame(){if(!running)return;paused=true;pause.classList.remove("hidden");pauseBtn.classList.remove("show")}
pauseBtn.onclick=pauseGame;
document.getElementById("play").onclick=start;document.getElementById("settings").onclick=()=>{menu.classList.add("hidden");settings.classList.remove("hidden")};document.getElementById("help").onclick=()=>{menu.classList.add("hidden");help.classList.remove("hidden")};document.getElementById("backSettings").onclick=()=>{settings.classList.add("hidden");menu.classList.remove("hidden")};document.getElementById("backHelp").onclick=()=>{help.classList.add("hidden");menu.classList.remove("hidden")};document.getElementById("restart").onclick=start;document.getElementById("home").onclick=()=>{over.classList.add("hidden");menu.classList.remove("hidden")};document.getElementById("resume").onclick=()=>{paused=false;pause.classList.add("hidden");pauseBtn.classList.add("show");last=performance.now();requestAnimationFrame(loop)};document.getElementById("restartPause").onclick=start;document.getElementById("homePause").onclick=()=>{paused=false;pause.classList.add("hidden");running=false;pauseBtn.classList.remove("show");scene.classList.remove("hidden");canvas.classList.add("hidden");menu.classList.remove("hidden")};
for(const id of ["musicToggle","soundToggle","vibeToggle"])document.getElementById(id).onclick=e=>e.currentTarget.classList.toggle("on");
scene.classList.remove("hidden");canvas.classList.add("hidden");
})();